name: 'Lighthouse CI Action'
description: 'Audit URLs using Lighthouse and test performance with Lighthouse CI'
inputs:
  urls:
    description: 'List of URL(s) to analyze'
  budgetPath:
    description: 'Path to a Lighthouse budgets.json file'
  configPath:
    description: 'Path to a LHCI lighthouserc.json file'
  uploadArtifacts:
    description: 'Opt-out of saving Lighthouse results as an action artifacts'
  temporaryPublicStorage:
    descripton: 'Opt-in to saving Lighthouse results to temporary public storage'
  runs:
    description: 'Number of runs to do per URL'
  serverBaseUrl:
    description: 'Address of a LHCI server'
  serverToken:
    description: 'API token to push to LHCI server'
  basicAuthUsername:
    description: 'Basic auth username for LHCI server'
  basicAuthPassword:
    description: 'Basic auth password for LHCI server'
outputs:
  resultsPath:
    description: 'Path to the folder with LHCI results'
  links:
    description: 'Links to compare/result UI for each URL (content of links.json)'
  assertionResults:
    description: 'Assertion results (content of assertion-results.json)'
runs:
  using: 'node12'
  main: 'src/index.js'
branding:
  icon: 'bar-chart-2'
  color: 'gray-dark'
