name: Run action locally
on: push
jobs:
  run-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Multiple URLs
        uses: ./
        with:
          urls: |
            https://alekseykulikov.com/
            https://alekseykulikov.com/blog
            https://alekseykulikov.com/not-found
          budgetPath: .github/lighthouse/budget.json
          extraHeaders: '{"x-github-action":"true"}'
      - name: One URL with custom config and options
        uses: ./
        with:
          url: 'https://alekseykulikov.com/'
          chromeFlags: '--window-size=1200,800'
          configPath: .github/lighthouse/desktop-config.js
          throttlingMethod: devtools
          onlyCategories: 'performance,seo'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-results
          path: './results'
